In [6]:
#1 Arrays
import numpy

input_data = input().split(' ')
reversed_array = numpy.fliplr(numpy.array([input_data],float))[0]

print(reversed_array)

1 3 5 2 4 6
[6. 4. 2. 5. 3. 1.]


In [9]:
#2 Shape and reshape
import numpy
a =input().strip().split(' ')
a=numpy.array(a)
print(numpy.reshape(a,(3,3)))

1 2 3 4 5 6 7 8 9
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [11]:
#3 Transpose and flatten
import numpy
n,m = map(int,input().split())
mat = numpy.array([[int(x) for x in input().split()] for k in range(n)])
print(numpy.transpose(mat))
print(mat.flatten())

2 4
3 4 5 6
2 3 4 5
[[3 2]
 [4 3]
 [5 4]
 [6 5]]
[3 4 5 6 2 3 4 5]


In [13]:
#4 Concatenate
import numpy

n,m,p=map(int,input().split())

lista1=[list(map(int,input().split())) for i in range(n)]
lista2=[list(map(int,input().split())) for i in range(m)]
a1=numpy.array(lista1)
a2=numpy.array(lista2)

print(numpy.concatenate((a1,a2),axis=0))

2 3 4
1 2 3 4
2 4 6 8
1 3 5 7
6 8 1 3
2 3 4 6
[[1 2 3 4]
 [2 4 6 8]
 [1 3 5 7]
 [6 8 1 3]
 [2 3 4 6]]


In [15]:
#5 zeroes and ones
import numpy
N = [int(x) for x in input().split()]
print(numpy.zeros(N, dtype = numpy.int))
print(numpy.ones(N, dtype = numpy.int))

2 2 2
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [19]:
#6 Eye and identity
import numpy
n,m =list(map(int,input().split()))
print(numpy.eye(n,m,k=0))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#7 Array mathematics
import numpy
n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
B=numpy.array([list(map(int,input().split())) for i in range(n)])
print(A+B,A-B,A*B,A//B,A%B,A**B,sep='\n')

1 3
2 3 4
5 6 7
[[ 7  9 11]]
[[-3 -3 -3]]
[[10 18 28]]
[[0 0 0]]
[[2 3 4]]
[[   32   729 16384]]


In [25]:
#8 Floor,ceil and rint
import numpy as np
a =np.array(list(map(float,input().split())))
print(np.ceil(a))
print(np.floor(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8
[2. 3. 4. 5. 6. 7. 8. 9.]
[1. 2. 3. 4. 5. 6. 7. 8.]
[1. 2. 3. 4. 6. 7. 8. 9.]


In [26]:
#9 sum and product
import numpy
n,m=map(int,input().split())
array=[list(map(int,input().split())) for i in range(n)]
print(numpy.prod(numpy.sum(array,axis=0),None))

2 4
1 2 3 4
2 4 6 8
1944


In [28]:
#10 Min and max
import numpy 
n,m = map(int,input().split())
a =[list(map(int,input().split()))for i in range(n)]
print(numpy.min(a),numpy.max(a),sep='\n')

3 3
1 2 3
4 5 6
7 8 9
1
9


In [1]:
#11 Mean Var and std
import numpy 
n,m = map(int,input().split())
a =[list(map(int,input().split()))for i in range(n)]
print(numpy.mean(a,axis=0),numpy.mean(a,axis=1),numpy.mean(a),numpy.var(a,axis=0),numpy.var(a,axis=1),numpy.var(a),numpy.std(a,axis=0),numpy.std(a,axis=1),numpy.std(a),sep='\n')

2 3
1 2 3
5 6 7
[3. 4. 5.]
[2. 6.]
4.0
[4. 4. 4.]
[0.66666667 0.66666667]
4.666666666666667
[2. 2. 2.]
[0.81649658 0.81649658]
2.160246899469287


In [6]:
#12 Dot and cross product
import numpy 
n =int(input())
a =[list(map(int,input().split()))for i in range(n)]
b =[list(map(int,input().split()))for i in range(n)]
print(numpy.dot(a,b),numpy.cross(a,b),sep='\n')

2
1 2
3 4
5 6
7 8
[[19 22]
 [43 50]]
[-4 -4]


In [9]:
#13 Inner and outer product
import numpy 
a =list(map(int,input().split()))
b =list(map(int,input().split()))
print(numpy.inner(a,b),numpy.outer(a,b),sep='\n')

1 2
3 4
11
[[3 4]
 [6 8]]


In [10]:
#14 Polynomials
import numpy
coefs=list(map(float,input().split()))
x=float(input())
print(numpy.polyval(coefs,x))

1 2
0
2.0


In [11]:
#15 Linear Algebra
import numpy
array=[list(map(float,input().split())) for i in range(int(input()))]
print(numpy.linalg.det(array))

2
1.1 1.1
1.1 1.1
0.0
